Changes to allow compilation on Windows
Iterating through bson iter to check if an array is destructive,
and is now passed in as a pointer opposed to just the bson_iter_t.

The error that passing the pointer is:
error C2710: 'iter': formal parameter with __declspec(align('128'))
won't be aligned

This is using
1) Windows 7
2) VS 2010 Express
3) Windows SDK 7.1